# Generated by Django 6.1.1 on 2026-10-09 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universidadId', models.IntegerField()),
                ('usuarioId', models.IntegerField()),
                ('texto', models.TextField()),
                ('calificacion', models.PositiveSmallIntegerField(default=5)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('universidadId', 'usuarioId')},
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universidadId', models.IntegerField()),
                ('usuarioId', models.IntegerField()),
            ],
            options={
                'unique_together': {('universidadId', 'usuarioId')},
            },
        ),
    ]
