# Generated by Django 6.0.3 on 2026-03-30 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PUB', 'Pública'), ('PRI', 'Privada')], max_length=3)),
                ('rating_google', models.FloatField(default=0.0)),
                ('sitio_web', models.URLField(blank=True)),
                ('google_place_id', models.CharField(max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Universidades',
                'ordering': ['-rating_google'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('favoritos', models.ManyToManyField(blank=True, related_name='seguidores', to='core.universidad')),
            ],
        ),
    ]
