# Generated by Django 6.0.3 on 2026-03-31 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universidad',
            name='descripcion_ia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universidad',
            name='foto_reference',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
