# Generated by Django 6.0.3 on 2026-04-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_universidad_descripcion_ia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universidad',
            name='sitio_web',
        ),
        migrations.AddField(
            model_name='universidad',
            name='google_maps_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universidad',
            name='sitio_oficial',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='universidad',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
