# Generated by Django 6.0.3 on 2026-04-07 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_universidad_sitio_web_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universidad',
            options={'ordering': ['-rating_google', 'nombre'], 'verbose_name_plural': 'Universidades'},
        ),
    ]
