# Generated by Django 6.0.3 on 2026-04-20 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_universidad_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='universidad',
            name='comentario',
            field=models.ManyToManyField(blank=True, to='core.perfil'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('calificacion', models.PositiveSmallIntegerField(default=5)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.universidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('universidad', 'usuario')},
            },
        ),
    ]
