# Generated by Django 6.1.1 on 2026-09-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PUB', 'Pública'), ('PRI', 'Privada')], max_length=3)),
                ('rating_google', models.FloatField(default=0.0)),
                ('google_maps_url', models.URLField(blank=True, null=True)),
                ('sitio_oficial', models.URLField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion_ia', models.TextField(blank=True, null=True)),
                ('foto_reference', models.CharField(blank=True, max_length=500, null=True)),
                ('google_place_id', models.CharField(max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Universidades',
                'ordering': ['-rating_google', 'nombre'],
            },
        ),
    ]
